name: Deploy to Stage

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or your project's Node.js version

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run ./tests/testcicd.postman_collection.json --reporters cli
          
      # Only if all tests pass, proceed to deploy
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.STAGE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Stage Server
        run: |
          ssh ${{ secrets.STAGE_USER }}@${{ secrets.STAGE_HOST }} << 'EOF'
            cd ${{ secrets.STAGE_PATH }}
            git pull origin stage
            npm install
            pm2 stop hha-stage
            pm2 start hha-stage
          EOF
